### Text request
GET http://localhost:8000/?input_type=text&query=cat
### Image request
GET http://localhost:8000/?input_type=image&query=https://flexible.img.hani.co.kr/flexible/normal/970/777/imgdb/resize/2019/0926/00501881_20190926.JPG

